### ISSUE TITLE
Command line "-" causes signal TYPE-ERROR

### ISSUE THREAD

**Issue by tlikonen** [astine/unix-options#1]
When command line contains a single hyphen "-" a condition of type `TYPE-ERROR` is signalled. More specifically, in SBCL it is `SB-INT:INVALID-ARRAY-INDEX-ERROR`.

To reproduce:

```
(unix-options:getopt '("-") "h" nil)
```

**Comment by flpa** [comment]
I can reproduce this, I think I'll look into that.
